# Generated by Django 2.2.28 on 2023-03-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(default='/', help_text="This should be an absolute path, excluding the domain name. Example: '/events/search/'.", max_length=200, unique=True, verbose_name='URL'),
        ),
    ]
